config/routes.rb
Rails.application.routes.draw do

  # devise_for :users, :controllers => {registrations: :restricted_registrations}
  devise_for :users

  get '/editor', :to => 'editor#show'
  get '/editor/:lang', :to => 'editor#show'
  get '/projects/:id/html', :to => 'projects#show'
  get '/projects/:id/css', :to => 'projects#show'
  get '/projects/:id/javascript', :to => 'projects#show'

  resources :rooms
  resources :projects
  resources :users

  root to: 'home#index'

  mount ActionCable.server => '/cable'

end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :user

  before_validation :wipe_slug

  def wipe_slug
    self.slug = nil
  end

  has_many :codes
  after_create_commit :attach_codes

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  def attach_codes
    Code.create! project_id: self.id, language: :html
    Code.create! project_id: self.id, language: :css
    Code.create! project_id: self.id, language: :javascript
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(user: current_user)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @messages = Message.where(:project_id => @project.id)
    @html_code = @project.codes[0].text
    @css_code = @project.codes[1].text
    @javascript_code = @project.codes[2].text
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class='project'>
  <div class='name'><%= project.name %></div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>
<%= render 'form', project: @project %>
<%= link_to 'Back', projects_path %>
<%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<ul id='projects'>
  <% @projects.each do |project| %>
    <%= link_to project do %>
     <li><%= render(project) %></li>
    <% end %>
  <% end %>
</ul>
<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div id='project' data-project-id='<%= @project.id %>'>
  <h1 class='project-name'>
    <%= link_to 'Projects', projects_path %> /
    <%= @project.name.capitalize %>
  </h1>
  <p class='project-description'> <%= @project.description %></p>
  <% if current_user == @project.user %>
  <%= link_to "Edit Project", edit_project_path(@project), class: :edit_project %>
  <% end %>
  <%= render 'editor/show' %>
  <%= render 'rooms/chat' %>
</div>